const historyData={
 precolonial:{tag:"Before 1565",title:"Pre-colonial communities",text:"Pre-colonial Philippine societies were diverse. Historical accounts describe women and men taking on different but sometimes overlapping social, economic, political, and spiritual roles. The status of women was not uniform across all communities.",points:["Women could hold property and participate in economic activity in some communities.","Babaylan and related spiritual roles show that authority was not exclusively male in some communities.","The pre-colonial Philippines should not be treated as one single social system."]},
 spanish:{tag:"1565–1898",title:"Spanish colonial period",text:"Spanish colonial rule brought institutional, religious, and social changes that influenced expectations surrounding family, sexuality, morality, education, and women's public roles. These changes were experienced differently across social groups.",points:["Catholic institutions became influential in social and family life.","Ideas about femininity and domesticity became important in many colonial contexts.","Gender expectations also intersected with class, location, and colonial status."]},
 american:{tag:"1898–1946",title:"American period",text:"The American colonial period expanded public education and introduced new institutions and opportunities. These developments contributed to changing ideas about women's education, employment, civic participation, and public life.",points:["Education became an important route for expanding opportunities.","Women's participation in public and professional life developed further.","New opportunities existed alongside continuing social expectations."]},
 postwar:{tag:"1946 onward",title:"Post-war Philippines",text:"After independence, family-centered expectations remained strong while women's participation in education, work, politics, and professional life continued to expand. Provider and homemaker ideals remained influential in many households.",points:["Men were often associated with breadwinning and authority.","Women were often associated with caregiving and domestic responsibilities.","Actual family arrangements varied across class, region, and circumstance."]},
 contemporary:{tag:"Today",title:"Contemporary Philippines",text:"Today, gender roles are being renegotiated in families, schools, workplaces, politics, and media. Traditional expectations remain visible, but people also challenge stereotypes and share responsibilities in different ways.",points:["The PSA maintains gender indicators across many social and economic sectors.","Gender equality and women's empowerment are part of national policy frameworks.","Contemporary experiences remain diverse rather than fitting one universal pattern."]}
};
const comparisons=[
 ["Men as primary providers","Shared responsibility","Men are often expected to carry the main financial responsibility of the household.","Many households negotiate income, caregiving, and domestic work according to their circumstances."],
 ["Women as homemakers","Multiple roles","Women have historically been associated strongly with domestic and caregiving work.","Women today participate across education, employment, entrepreneurship, public life, and family roles."],
 ["Caregiving as feminine","Caregiving as shared work","Care work is often treated as a responsibility belonging mainly to women.","Caregiving can be shared among parents, relatives, and other household members."],
 ["Gendered career choices","Broader career possibilities","Social expectations can make some occupations appear more suitable for one gender.","People increasingly challenge the idea that a career should be determined by gender."]
];
let comparisonIndex=0;
function renderHistory(key){const data=historyData[key],panel=document.getElementById("history-panel");panel.innerHTML=`<div><div class="period-tag">${data.tag}</div><h3>${data.title}</h3></div><div><p>${data.text}</p><ul>${data.points.map(p=>`<li>${p}</li>`).join("")}</ul></div>`}
document.querySelectorAll(".timeline-item").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".timeline-item").forEach(b=>{b.classList.remove("active");b.setAttribute("aria-selected","false")});button.classList.add("active");button.setAttribute("aria-selected","true");renderHistory(button.dataset.period)}));
function renderComparison(){const item=comparisons[comparisonIndex];document.getElementById("compare-old-title").textContent=item[0];document.getElementById("compare-new-title").textContent=item[1];document.getElementById("compare-old-text").textContent=item[2];document.getElementById("compare-new-text").textContent=item[3];document.getElementById("comparison-dots").innerHTML=comparisons.map((_,i)=>`<span class="dot ${i===comparisonIndex?"active":""}"></span>`).join("")}
document.getElementById("swap-btn").addEventListener("click",()=>{comparisonIndex=(comparisonIndex+1)%comparisons.length;renderComparison()});
const modal=document.getElementById("modal"),modalTitle=document.getElementById("modal-title"),modalText=document.getElementById("modal-text");
function openModal(title,text){modalTitle.textContent=title;modalText.textContent=text;modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.querySelector(".modal-close").focus()}
function closeModal(){modal.classList.remove("open");modal.setAttribute("aria-hidden","true")}
document.querySelectorAll(".modal-trigger,.expectation,.voice-card").forEach(el=>el.addEventListener("click",()=>openModal(el.dataset.title,el.dataset.text)));
document.querySelector(".modal-close").addEventListener("click",closeModal);document.querySelector(".modal-backdrop").addEventListener("click",closeModal);document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
const menuToggle=document.querySelector(".menu-toggle"),navLinks=document.querySelector(".nav-links");menuToggle.addEventListener("click",()=>{const open=navLinks.classList.toggle("open");menuToggle.setAttribute("aria-expanded",String(open))});document.querySelectorAll(".nav-links a").forEach(a=>a.addEventListener("click",()=>navLinks.classList.remove("open")));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add("visible")}),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));
const toTop=document.getElementById("to-top");window.addEventListener("scroll",()=>toTop.classList.toggle("show",window.scrollY>500));toTop.addEventListener("click",()=>window.scrollTo({top:0,behavior:"smooth"}));
renderHistory("precolonial");renderComparison();
